import type {Dataset} from './risk';
const at='2026-09-06T10:00:00.000Z';
export const demo:Dataset={name:'Meridian Financial • Sample enterprise',demo:true,assets:[
{id:'a1',name:'Core banking API',unit:'Digital Banking',owner:'Platform engineering',service:'Customer transactions',criticality:5,dependencies:['a2','a3']},
{id:'a2',name:'Customer data warehouse',unit:'Digital Banking',owner:'Data engineering',service:'Customer records',criticality:5,dependencies:[]},
{id:'a3',name:'Identity provider',unit:'Enterprise IT',owner:'Identity team',service:'Workforce authentication',criticality:5,dependencies:[]},
{id:'a4',name:'Payment gateway',unit:'Payments',owner:'Payments engineering',service:'Payment processing',criticality:5,dependencies:['a3']},
{id:'a5',name:'Employee endpoints',unit:'Enterprise IT',owner:'IT operations',service:'Workforce productivity',criticality:3,dependencies:['a3']},
{id:'a6',name:'Cloud storage',unit:'Digital Banking',owner:'Cloud security',service:'Statement archive',criticality:4,dependencies:[]},
{id:'a7',name:'Recovery infrastructure',unit:'Enterprise IT',owner:'Infrastructure team',service:'Business continuity',criticality:4,dependencies:[]},
{id:'a8',name:'Partner access gateway',unit:'Payments',owner:'Network security',service:'Third-party connectivity',criticality:4,dependencies:['a4']}],risks:[
{id:'r1',assetId:'a1',name:'Internet-facing API exploitation',category:'Application compromise',source:'Vulnerability management',finding:'Critical patch backlog on exposed API hosts',frequency:.7,cvss:9.8,threat:1.5,control:.35,downtime:6000000,breach:12000000,penalty:3000000,reputation:4000000,uncertainty:.65,observedAt:at},
{id:'r2',assetId:'a3',name:'Privileged account takeover',category:'Identity compromise',source:'IAM',finding:'18 of 42 privileged accounts lack phishing-resistant MFA',frequency:.8,cvss:8.2,threat:1.2,control:.42,downtime:5000000,breach:7000000,penalty:1500000,reputation:2500000,uncertainty:.6,observedAt:at},
{id:'r3',assetId:'a4',name:'Payment service ransomware',category:'Ransomware',source:'EDR',finding:'Incomplete isolation coverage on payment hosts',frequency:.6,cvss:8.8,threat:1.3,control:.45,downtime:14000000,breach:3000000,penalty:1000000,reputation:3000000,uncertainty:.75,observedAt:at},
{id:'r4',assetId:'a2',name:'Customer record exfiltration',category:'Data breach',source:'SIEM',finding:'Unusual bulk export activity with limited egress detection',frequency:.4,cvss:7.6,threat:1.1,control:.55,downtime:1000000,breach:16000000,penalty:5000000,reputation:4000000,uncertainty:.8,observedAt:at},
{id:'r5',assetId:'a6',name:'Public cloud data exposure',category:'Cloud misconfiguration',source:'CSPM',finding:'Statement archive permits overly broad access',frequency:.5,cvss:7.5,threat:1,control:.48,downtime:500000,breach:5000000,penalty:1500000,reputation:2000000,uncertainty:.55,observedAt:at},
{id:'r6',assetId:'a5',name:'Endpoint malware propagation',category:'Ransomware',source:'EDR',finding:'26 endpoints have stale protection policies',frequency:.9,cvss:7,threat:1.15,control:.62,downtime:3000000,breach:1000000,penalty:0,reputation:500000,uncertainty:.5,observedAt:at},
{id:'r7',assetId:'a7',name:'Recovery failure after incident',category:'Recovery failure',source:'Asset inventory',finding:'Backup restoration evidence is older than 90 days',frequency:.25,cvss:6.5,threat:1,control:.3,downtime:8000000,breach:0,penalty:500000,reputation:1500000,uncertainty:.7,observedAt:at},
{id:'r8',assetId:'a8',name:'Third-party lateral movement',category:'Third-party compromise',source:'Threat intelligence',finding:'Partner subnet has excessive reach into payment network',frequency:.35,cvss:8,threat:1.25,control:.5,downtime:4000000,breach:3000000,penalty:1000000,reputation:1000000,uncertainty:.65,observedAt:at}],actions:[
{id:'patch',name:'Patch exposed critical services',description:'Deploy critical fixes to API hosts, then verify with authenticated rescans.',cost:1800000,effects:{r1:.72,r3:.12},days:7,owner:'Platform engineering',frameworks:['NIST PR.PS','CIS 7','ISO A.8.8']},
{id:'mfa',name:'Enforce privileged MFA',description:'Require phishing-resistant MFA and revoke legacy privileged sessions.',cost:2400000,effects:{r2:.78,r4:.12,r8:.15},days:14,owner:'Identity team',frameworks:['NIST PR.AA','CIS 6','ISO A.8.5']},
{id:'segment',name:'Segment payment infrastructure',description:'Restrict east-west traffic and isolate partner connections.',cost:4200000,effects:{r3:.5,r8:.65,r1:.1},days:30,owner:'Network security',frameworks:['NIST PR.IR','CIS 12','ISO A.8.22']},
{id:'edr',name:'Extend endpoint detection coverage',description:'Close sensor gaps and validate automated containment.',cost:2600000,effects:{r3:.4,r6:.68},days:21,owner:'Security operations',frameworks:['NIST DE.CM','CIS 10','ISO A.8.7']},
{id:'cloud',name:'Lock down cloud storage access',description:'Remove public permissions and apply least-privilege storage policies.',cost:600000,effects:{r5:.8},days:3,owner:'Cloud security',frameworks:['NIST PR.DS','CIS 3','ISO A.8.3']},
{id:'monitor',name:'Detect anomalous data exports',description:'Add behavioral alerts for bulk exports and validate triage workflows.',cost:1500000,effects:{r4:.55,r2:.1},days:10,owner:'Security operations',frameworks:['NIST DE.CM','CIS 13','ISO A.8.16']},
{id:'backup',name:'Validate immutable recovery',description:'Test isolated backups and measure restoration time.',cost:2100000,effects:{r7:.7,r3:.2,r6:.15},days:14,owner:'Infrastructure team',frameworks:['NIST RC.RP','CIS 11','ISO A.8.13']} ]};
