export type Asset={id:string;name:string;unit:string;owner:string;service:string;criticality:number;dependencies:string[]};
export type Risk={id:string;assetId:string;name:string;category:string;source:string;finding:string;frequency:number;cvss:number;threat:number;control:number;downtime:number;breach:number;penalty:number;reputation:number;uncertainty:number;observedAt:string};
export type Action={id:string;name:string;description:string;cost:number;effects:Record<string,number>;days:number;owner:string;frameworks:string[]};
export type Dataset={name:string;demo:boolean;assets:Asset[];risks:Risk[];actions:Action[]};
export const money=(n:number)=>Math.abs(n)>=1e7?`₹${(n/1e7).toFixed(2)} Cr`:Math.abs(n)>=1e5?`₹${(n/1e5).toFixed(1)} L`:`₹${Math.round(n).toLocaleString('en-IN')}`;
export function quantify(d:Dataset,selected:string[]=[],delay=0){return d.risks.map(r=>{const a=d.assets.find(a=>a.id===r.assetId)!;const severity=r.downtime+r.breach+r.penalty+r.reputation;const lambda=r.frequency*(.5+r.cvss/10)*r.threat*(1-r.control)*(a.criticality/3);const residual=d.actions.filter(a=>selected.includes(a.id)).reduce((p,a)=>p*(1-(a.effects[r.id]||0)),1);const effective=delay/365+(1-delay/365)*residual;const eal=lambda*severity*effective;return {...r,asset:a,lambda:lambda*effective,likelihood:1-Math.exp(-lambda*effective),severity,eal};}).sort((a,b)=>b.eal-a.eal)}
export function total(d:Dataset,ids:string[]=[],delay=0){return quantify(d,ids,delay).reduce((s,r)=>s+r.eal,0)}
export function optimize(d:Dataset,budget:number){const base=total(d);let best={ids:[] as string[],cost:0,reduction:0};for(let mask=0;mask<2**d.actions.length;mask++){const acts=d.actions.filter((_,i)=>mask&(1<<i));const cost=acts.reduce((s,a)=>s+a.cost,0);if(cost>budget)continue;const ids=acts.map(a=>a.id);const reduction=base-total(d,ids);if(reduction>best.reduction+1e-6||(Math.abs(reduction-best.reduction)<1e-6&&cost<best.cost))best={ids,cost,reduction};}return best}
export function simulate(d:Dataset,ids:string[]=[],iterations=5000){let seed=431;const rand=()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return (seed+.5)/4294967296};const risks=quantify(d,ids);const losses=[];for(let i=0;i<iterations;i++){let loss=0;for(const r of risks){const limit=Math.exp(-r.lambda);let p=1,k=0;do{k++;p*=rand()}while(p>limit&&k<1000);for(let j=0;j<k-1;j++){const z=Math.sqrt(-2*Math.log(rand()))*Math.cos(2*Math.PI*rand());const sigma=r.uncertainty;loss+=r.severity*Math.exp(sigma*z-sigma*sigma/2)}}losses.push(loss)}losses.sort((a,b)=>a-b);return {p50:losses[Math.floor(iterations*.5)],p95:losses[Math.floor(iterations*.95)],p99:losses[Math.floor(iterations*.99)],mean:losses.reduce((s,n)=>s+n,0)/iterations}}
export function forecast(rows:{eal:number;createdAt:string}[]){if(rows.length<3)return null;const t0=Date.parse(rows[0].createdAt);const pts=rows.map(r=>({x:(Date.parse(r.createdAt)-t0)/86400000,y:r.eal}));const x=pts.reduce((s,p)=>s+p.x,0)/pts.length,y=pts.reduce((s,p)=>s+p.y,0)/pts.length;const denominator=pts.reduce((s,p)=>s+(p.x-x)**2,0);if(denominator<1)return null;const slope=pts.reduce((s,p)=>s+(p.x-x)*(p.y-y),0)/denominator;return {daily:slope,value:Math.max(0,y+slope*(Math.max(...pts.map(p=>p.x))+30-x))}}
